name:
  en: Open GitHub Repo
  zh-Hans: 打开 GitHub 项目
  zh-Hant: 開啟 GitHub 倉庫
  ja: GitHub リポジトリを開く
version: 2
icon: github.png
popclip version: 693
identifier: org.phpz.popclip.extension.open-github-repo
description: Open GitHub Repo in a web browser with the selected text like AUTHOR/REPO.
action:
  title:
    en: Open GitHub Repo
    zh-Hans: 打开 GitHub 项目
    zh-Hant: 開啟 GitHub 倉庫
    ja: GitHub リポジトリを開く
  icon: github.png
  regex: ^\s*[\w\-\.]+/[\w\-\.]+\s*$
  requirements: [text]
  javascript: popclip.openUrl('https://github.com/' + popclip.input.text);
