name:
  en: PinYin
  zh-Hans: 拼音
  zh-Hant: 拼寫
version: 2
identifier: xyz.phpz.popclip.extension.pinyin
icon: 拼
description:
  en: convert Chinese characters to pinyin.
  zh-Hans: 将中文字符转换为拼音.
  zh-Hant: 將中文字符轉換為拼寫.
options:
  # - identifier: read_it
  #   label:
  #     en: Read Selected Text
  #     zh-Hans: 朗读所选文本
  #     zh-Hant: 讀出所選文字
  #   type: boolean
  #   default value: true
  - identifier: tone_type
    label:
      en: Tone Type
      zh-Hans: 音调类型
      zh-Hant: 音調類型
    type: multiple
    values: [mark, number, alphabet]
    value labels:
      - en: Tone Mark (pīn)
        zh-Hans: 音调标记 (pīn)
        zh-Hant: 音調標記 (pīn)
      - en: Tone Number (pin1)
        zh-Hans: 音调数字 (pin1)
        zh-Hant: 音調數字 (pin1)
      - en: Tone Alphabet (pin)
        zh-Hans: 无音调 (pin)
        zh-Hant: 無音調 (pin)
action:
  javascript file: pinyin.js
  after: show-result
