# Yaml Config File
# DOCS: https://www.popclip.app/dev/packages
identifier: your.domain.popclip.extension.template_module
description: Description
icon: square filled M
name:
  en: 'Name'
  zh-Hans: '名称'
  zh-Hant: '名稱'
  ja: '名前'
options:
  - identifier: option-a
    label: Option A
    type: boolean
    default value: true
module: Main.ts